rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-19mode

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  allow_failures:
    - rvm: 1.8.7